%print chinfos in an Excel-friendly format
% animals = {'Adobo_LT', 'Caraway_LT', 'Chives_LT', ...
%     'Cinnamon_LT', 'Coriander_LT', 'Fenugreek_LT', 'GaramMasala_LT', 'Salt_LT', ...
%     'Baharat_LT', 'Cardamom_LT', 'Jerk_LT', 'Mace_LT', 'Mustard_LT', ...
%     'Tarragon_LT', 'Vanilla_LT',...
%     'Basil_LT', 'Cumin_LT', 'Dill_LT', 'Nutmeg_LT', 'Paprika_LT', 'Parsley_LT', 'Sumac_LT',... 
%     'Pepper_LT', 'Sage_LT', 'Anise_LT', 'Thyme_LT', 'OldBay_LT', 'Rosemary_LT',...
%     'Provence_LT', 'Saffron_LT'};

E3 = {'r1_01_', 'r1_12_', 'r1_18_', 'r1_21_', 'r1_29_', 'r1_33_', 'r1_34_',  'r1_39_',...
    'r2_06_', 'r2_17_', 'r2_28_',...
    'r3_02_', 'r3_11_'};
E4 = {'r1_05_', 'r1_24_', 'r1_31_', 'r1_35_', ...
    'r2_08_', 'r2_13_', 'r2_14_', 'r2_26_', 'r2_27_', 'r2_36_', 'r2_38_',...
    'r3_04_', 'r3_09_', 'r3_20_', 'r3_32_', 'r3_40_'};
animals = [E4];

animalbasedir = 'D:\Cohort 1\E4KI';
for a = 1:length(animals)
    prefix = animals{a};
    load(sprintf('%s/%s/%schinfo.mat',animalbasedir,prefix,prefix))
	fprintf('%s\n',prefix)
	c = chinfo{1}{1};
	for i = 1:8
		fprintf('%d %s %s\t%d %s %s\t%d %s %s\t%d %s %s\n',i,c{i}.area,c{i}.layer,i+8,c{i+8}.area,c{i+8}.layer,i+16,c{i+16}.area,c{i+16}.layer,i+24,c{i+24}.area,c{i+24}.layer)
	end
end